# -*- coding: utf-8 -*-
{
    'name': 'SPS Projects',
    'version': '14.0.0.2.8',
    'description': '',
    'author': 'THG',
    'website': '',
    'license': 'OPL-1',
    'category': 'Services/Project',
    'depends': ['project', 'product', 'sale', 'hr', 'xhr', 'xhr_payroll', 'sps_sale_target', 'account_advanced', 'xpurchase'],
    'data': [
        'data/data.xml',
        'security/security.xml',
        'security/ir.model.access.csv',
        'views/views.xml',
        'views/expertise.xml',
        'views/product.xml',
        'views/project_depreciation_view.xml',
        'views/project.xml',
        'views/sale_request.xml',
        'views/sale_order.xml',
        'views/hr_work_entry_views.xml',
        'views/hr_employee_views.xml',
        'views/assets.xml',

        'wizards/employee_calendar.xml',
        'wizards/customer_satisfaction.xml',
        'wizards/manpower_weekly.xml',
        'wizards/manpower_yearly.xml',
        'wizards/manpower_efficiency.xml',
        'wizards/manhour_rate.xml',
    ],
    'auto_install': False,
    'application': False,
}
